services:
  video_in:
    image: containers.openfilter.io/plainsightai/openfilter-video-in:v0.1.10
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-}
      FILTER_ID: VideoIn
      FILTER_SOURCES: file:///video.mp4!sync!loop
      FILTER_OUTPUTS: tcp://*
    volumes:
      - ./data/sample-video.mp4:/video.mp4:ro

  aggregator_filter:
    image: containers.openfilter.io/plainsightai/openfilter-aggregator:v1.1.3
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-}
      FILTER_ID: AggregatorFilter
      FILTER_SOURCES: tcp://video_in
      FILTER_OUTPUTS: tcp://*
      FILTER_MQ_LOG: pretty

  webvis:
    image: containers.openfilter.io/plainsightai/openfilter-webvis:v0.1.10
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-}
      FILTER_ID: Webvis
      FILTER_SOURCES: tcp://aggregator_filter
    ports:
      - 8001:8000