services:
  video_in:
    image: containers.openfilter.io/plainsightai/openfilter-video-inopenfilter-aggregator:1.1.5
    environment:
      LOG_LEVEL: ${LOG_LEVELopenfilter-aggregator:1.1.5}
      FILTER_ID: VideoIn
      FILTER_SOURCES: file:///video.mp4!sync!loop
      FILTER_OUTPUTS: tcp://*
    volumes:
      - ./data/sample-video.mp4:/video.mp4openfilter-aggregator:1.1.5

  aggregator_filter:
    image: containers.openfilter.io/plainsightai/openfilter-aggregator:1.1.5
    environment:
      LOG_LEVEL: ${LOG_LEVELopenfilter-aggregator:1.1.5}
      FILTER_ID: AggregatorFilter
      FILTER_SOURCES: tcp://video_in
      FILTER_OUTPUTS: tcp://*
      FILTER_MQ_LOG: pretty

  webvis:
    image: containers.openfilter.io/plainsightai/openfilter-webvisopenfilter-aggregator:1.1.5
    environment:
      LOG_LEVEL: ${LOG_LEVELopenfilter-aggregator:1.1.5}
      FILTER_ID: Webvis
      FILTER_SOURCES: tcp://aggregator_filter
    ports:
      - 8001openfilter-aggregator:1.1.5